#Put default max values of stuff in here
quests:
  kill:
    quest1:
      name: Zombie Slayer
      description: Kill a zombie
      reward: 100
      target:
        type: ZOMBIE
        count: 1
    quest2:
      name: Genocide
      description: Kill 5 Villagers
      reward: 400
      target:
        type: VILLAGER
        count: 5