name: Kingdoms
version: '${project.version}'
main: games.kingdoms.kingdoms.Kingdoms
api-version: 1.17
authors: [ YBR_Bleach ]
description: Commands for the Kingdoms Project!
website: www.kingdoms.games
depend: [Labyrinth]
load: POSTWORLD
commands:
  staffvault:
    description: Access OP Staff Items!
    aliases: [sv]
  nv:
    description: Give or remove night vision from yourself.
    aliases: [nightvision]
  rtp:
    description: Randomly teleport yourself.
    aliases: []
  feed:
    description: Sate yourself!
    aliases: [sate]
  fly:
    description: Fly!
    aliases: []
  kingdom:
    description: Base command for all Kingdom commands.
    aliases: [k]
  warzone:
    description: Teleport to the warzone.
    aliases: [wz]
  vanish:
    description: Vanish from players.
    aliases: [v]
  chat:
    description: Switch between chat channels.
    aliases: [c]
  rank:
    description: Set a player's rank.
    aliases: []
  nick:
    description: Nickname yourself.
    aliases: [nickname]
  merchant:
    description: Select which items you can and can't sell to the Merchant.
    aliases: []
  gmc:
    description: Set your gamemode to Creative.
    aliases: []
  gma:
    description: Set your gamemode to Adventure.
    aliases: []
  gms:
    description: Set your gamemode to Survival.
    aliases: []
  gmsp:
    description: Set your gamemode to Spectator.
    aliases: []